name: zampy_app
description: "ZamPy — App móvil para gestión de menús digitales."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  webview_flutter: ^4.10.0
  geolocator: ^14.0.2
  stomp_dart_client: ^3.0.1
  flutter_local_notifications: ^17.2.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
